### ISSUE TITLE
Add system `SystemParameters` as `@entity`

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/subgraph-cosmos-proposals#7]
## Tasks
- [ ] Define how we want to call `@entity` for System Parameters (ex: `SystemParameters` ?)
- [ ] Emit single entity for Genesis Params (defined in `params`)
  - we might need to use Substreams `store` to emit a single Entity on init
- [ ] Keep track of new system parameter changes, emit as `@entity`
